title: GPU Puzzlers
author: Adnan Aziz and Anupam Bhatnagar
description: On GPUs, PyTorch and CUDA.

  #github_username: anupambhatnagar
  #linkedin_username: bhatnagaranupam

  #social_media:
  #- { name: GitHub, fa_icon: fa-github-square, link: "https://github.com/anupambhatnagar" }
  #- { name: LinkedIn, fa_icon: fa-linkedin-square, link: "https://linkedin.com/in/bhatnagaranupam" }

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

paginate: 8
paginate_path: "/page:num/"

header_pages:
  - about.md
    #- quotes.md

markdown: kramdown
